# Generated by Django 5.2.6 on 2025-09-09 07:20

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование"
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=100, verbose_name="Модель"),
                ),
                ("release_date", models.DateField(verbose_name="Дата релиза")),
            ],
        ),
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название звена",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail", "Розничная сеть"),
                            ("entrepreneur", "Индивидуальный предприниматель"),
                        ],
                        max_length=20,
                        verbose_name="Тип звена",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "country",
                    models.CharField(max_length=100, verbose_name="Страна"),
                ),
                (
                    "city",
                    models.CharField(max_length=100, verbose_name="Город"),
                ),
                (
                    "street",
                    models.CharField(max_length=100, verbose_name="Улица"),
                ),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="Номер дома"),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                        verbose_name="Задолженность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Уровень звена"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="network.networknode",
                        verbose_name="Поставщик",
                    ),
                ),
                ("products", models.ManyToManyField(to="network.product")),
            ],
        ),
    ]
