# Generated by Django 5.2.6 on 2025-09-09 02:24

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="house_number",
            field=models.CharField(max_length=10, verbose_name="Номер дома"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="contact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="network.contact",
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создан"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
                verbose_name="Задолженность",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="level",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Уровень звена"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название звена"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("factory", "Завод"),
                    ("retail", "Розничная сеть"),
                    ("entrepreneur", "Индивидуальный предприниматель"),
                ],
                max_length=20,
                verbose_name="Тип звена",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="network.networknode",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(max_length=100, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(verbose_name="Дата релиза"),
        ),
    ]
